language: minimal

services:
  - docker

before_install:
  - ./ci/ci.sh detect_version

script:
  - ./ci/ci.sh build
  # - ./ci/ci.sh fmt

deploy:
  provider: releases
  name: test
  overwrite: true
  edge: true
