language: minimal

services:
  - docker

before_install:
  - ./ci/ci.sh detect_version

script:
  - export LHPROXY_VERSION="$(cat build/version.txt)"
  - ./ci/ci.sh build
  - ./ci/ci.sh fmt
  - export GITHUB_NAME="$LHPROXY_VERSION"

deploy:
  provider: releases
  name: test
  overwrite: true
  draft: true
  file: build/pack/*
  edge: true
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^lhproxy-.*$
