language: minimal

services:
  - docker

before_install:
  - ./ci/ci.sh detect_version

script:
  - export LHPROXY_VERSION="$(cat build/version.txt)"
  - export GITHUB_TAG_NAME="$LHPROXY_VERSION"
  - ./ci/ci.sh build
  # - ./ci/ci.sh fmt

deploy:
  provider: releases
  name: test
  overwrite: true
  draft: true
  edge: true
